name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  docker:
    needs: [Run-Pytest, coverage, snyk-analysis]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.EX2_PAT }} 

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/docker-image:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/docker-image:latest