name: Python Tests

on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 

jobs:
  Run-Pytest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event for the repository ${{ github.repository }}."
      - run: echo "Running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The branch being tested is ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The repository has been cloned into ${{ github.workspace }}."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: echo "Installing dependencies..."
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install coverage

      - run: echo "Running tests with parallel execution and measuring coverage..."
      - name: Run tests with pytest and coverage
        run: |
          pytest --cov=./ --cov-report=xml --numprocesses=auto

      - run: echo "Listing repository files after tests..."
      - name: List files in repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "Test run status ${{ job.status }}."
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  code_climate_coverage:
    needs: Run-Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Download Code Climate test reporter
        run: |
          curl -L https://github.com/codeclimate/test-reporter/releases/download/v0.11.1/codeclimate-test-reporter-linux-amd64 -o cc-test-reporter
          chmod +x cc-test-reporter
          
          # Verify download was successful
          if [ ! -s cc-test-reporter ]; then
            echo "Download failed or file is empty."
            exit 1
          fi
          echo "Code Climate test reporter downloaded successfully."

      - name: Upload coverage to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./cc-test-reporter format-coverage -t coverage.py -o coverage.xml
          ./cc-test-reporter upload-coverage